services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    PDO:
        class: PDO
        factory: ['App\Infrastructure\DatabaseConnectionFactory', 'create']
